language: node_js
node_js:
  - 21.7.2

before_script:
  - yarn install

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: main

notifications:
  on_success: false
  on_failure: change
