version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      # Add your build steps here
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build React App
          command: yarn build

  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "ratherblue@gmail.com"
            git config --global user.name "ratherblue"
            npm install -g gh-pages
            echo "Setting up GitHub Pages"
            yarn build
            gh-pages -d build
    requires:
      - build
    filters:
      branches:
        only:
          - main
